StudyMate/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StudyMate.Models
{
    public class Login
    {
        [Key]
        public int LoginId { get; set; }
        public string UserEmail { get; set; }
        public string PasswordHash { get; set; }
        public virtual Student Student { get; set; }
    }
}

StudyMate/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using StudyMate.Data;
using StudyMate.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static StudyMate.Controllers.DbHelper;

namespace StudyMate.Controllers
{
    public class LoginController : Controller
    {
        private AppDbContext _db;

        public IActionResult Index()
        {
            return View();
        }
        public LoginController(AppDbContext db)
        {
            _db = db;
        }
        public ActionResult Profile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login Login)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var email = Login.UserEmail;
            var student = await queryStudent(_db, email);

            if (student == null)
            {
                ModelState.AddModelError("Email", "Invalid email or password");
                return this.View(Login);
            }

            if (student.PasswordHash == Login.PasswordHash)
            {
                var password = Login.PasswordHash;
                var studentHome = new Student();
                return RedirectToAction("Index", "Profile", studentHome);
            }
            else
            {
                ModelState.AddModelError("Email", "Invalid email or password");
                return this.View();
            }

            /*IActionResult result = View();
            if (ModelState.IsValid)
            {
                var student = _db.Students.Where(e => e.EmailId == Login.UserEmail).FirstOrDefault();
                if (student != null)
                {
                    result = RedirectToAction("~/Profile");
                } else
                {
                    Response.Redirect("");
                    ViewBag.Message = "User does not exist or password did not match.";
                }
            }*/

        }
    }
}

StudyMate/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using StudyMate.Data;
using StudyMate.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudyMate.Controllers
{
    public class ProfileController : Controller
    {
        private AppDbContext _db;

        public ProfileController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(Student student)
        {
            return View(student);
        }
    }
}

StudyMate/Controllers/SignupController.cs
using Microsoft.AspNetCore.Mvc;
using StudyMate.Data;
using StudyMate.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudyMate.Controllers
{
    public class SignupController : Controller
    {
        private AppDbContext _db;
        public IActionResult Index()
        {
            return View();
        }
        public SignupController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Signup(Student Student)
        {
            
            if (ModelState.IsValid)
            {
                //var newVendor = new SmiPIM.Database.Models.Vendor { Name = vendor.Name };
                var newStudent = new Student { Name = Student.Name, EmailId = Student.EmailId, Major = Student.Major, PasswordHash = Student.PasswordHash };
                _db.Add(newStudent);
                _db.SaveChanges();
            }
            return RedirectToAction("index", "profile", Student);
        }
    }
}

StudyMate/Views/Shared/Login.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/responsive.css" />

<div class="text-center">
    <h1 class="display-4 responsive">Study Mate</h1>
    <p>Welcome to Study Mate <a asp-controller="Study Mate" asp-action="Index"></a></p>
    <div class="container">
        <div class="row searchFilter">
            <div class="col-sm-12">
                <div class="input-group">
                    <input id="searchString" type="search" class="form-control" placeholder="Find your study mate here....">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="label-icon">Filter</span> <span class="caret">&nbsp;</span></button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="filter_filters">
                                <li>
                                    <input class="cat_type filter-input" data-label="All" id="all" value="" name="radios" type="radio"><label for="all">All</label>
                                </li>
                                <li>
                                    <input type="radio" name="radios" id="Standing Class" value="Standing Class"><label class="category-label" for="Standing Class">Standing Class</label>
                                </li>
                                <li>
                                    <input type="radio" name="radios" id="Major" value="Major"><label class="category-label" for="Major">Major</label>
                                </li>

                            </ul>
                        </div>
                        <button id="searchBtn" type="button" class="btn btn-secondary btn-search" asp-area="" asp-controller="Home" asp-action="Search"><span class="glyphicon glyphicon-search">&nbsp;</span> <span class="label-icon">Search</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>





    <script src="./js/bootstrap.bundle.min.js"></script>
</div>

StudyMate/Views/Shared/_Layout.cshtml
<style>
    .navbar {
        position: sticky;
        top: 0;
        z-index: 100;
    }
    .floatClass {
        float: right;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<style>

</style>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudyMate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Study Mate</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item floatClass" style ="position:relative; left:75%;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Signup" asp-action="Index">Sign Up</a>
                        </li>
                        <li class="nav-item floatClass" style ="position:relative; left:75%;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StudyMate - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StudyMate/Views/Shared/_StudentInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@@
@model IEnumerable<Student>

@{
    ViewData["Title"] = "Your potential study mates";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    #container {
        padding: 10px;
        background-color: aliceblue;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    a.button1, a.button2, a.button3 {
        display: inline-block;
        padding-right: 7px;
        padding-left: 7px;
        border: 0.16px solid black;
        border-radius: 5px;
        box-sizing: border-box;
        text-decoration: none;
        text-transform: uppercase;
        font-family: 'Roboto',sans-serif;
        font-weight: 400;
        color: black;
        text-align: center;
        transition: all 0.15s;
    }

        a.button1:hover {
            color: black;
            border-color: black;
            cursor: pointer;
            background-color: green;
        }

        a.button2:hover {
            color: black;
            border-color: black;
            cursor: pointer;
            background-color: Highlight;
        }

        a.button3:hover {
            color: black;
            border-color: black;
            cursor: pointer;
            background-color: red;
        }

        a.button1 a.button2 a.button3:active {
            color: tan;
            border-color: firebrick;
        }

    #hovertext1 {
        position: relative;
        border-bottom: 1px dotted black;
    }

    #hovertext2 {
        position: relative;
        border-bottom: 1px dotted black;
    }

    #hovertext3 {
        position: relative;
        border-bottom: 1px dotted black;
    }

    #hovertext1:before {
        content: attr(data-hover);
        visibility: hidden;
        opacity: 0;
        width: 70px;
        background-color: green;
        color: #fff;
        text-align: center;
        border-radius: 5px;
        transition: opacity 1s ease-in-out;
        position: absolute;
        z-index: 1;
        left: -150%;
        top: 1%;
    }

    #hovertext2:before {
        content: attr(data-hover);
        visibility: hidden;
        opacity: 0;
        width: 70px;
        background-color: Highlight;
        color: #fff;
        text-align: center;
        border-radius: 5px;
        transition: opacity 1s ease-in-out;
        position: absolute;
        z-index: 1;
        left: -150%;
        top: 1%;
    }

    #hovertext3:before {
        content: attr(data-hover);
        visibility: hidden;
        opacity: 0;
        width: 70px;
        background-color: red;
        color: #fff;
        text-align: center;
        border-radius: 5px;
        transition: opacity 1s ease-in-out;
        position: absolute;
        z-index: 1;
        left: -150%;
        top: 1%;
    }

    #hovertext1:hover:before {
        opacity: 1;
        visibility: visible;
    }

    #hovertext2:hover:before {
        opacity: 1;
        visibility: visible;
    }

    #hovertext3:hover:before {
        opacity: 1;
        visibility: visible;
    }
</style>

<table width="94%" align="center">
    <thead>
        <tr>
            <th width="20%">@Html.DisplayNameFor(model => model.Name)</th>
            <th width="20%">@Html.DisplayNameFor(model => model.Major)</th>
            <th width="10%">@Html.DisplayNameFor(model => model.EmailId)</th>
            

            <th width="30%">Actions for Administrators</th>
            <th width="10%">Actions for Users</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>


            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.Major)
            </td>
            <td class="align-middle">
                @Html.DisplayFor(modelItem => item.EmailId)
            </td>

            

            <td class="align-middle">
                <a class="btn btn-outline-primary" asp-action="Update" asp-route-id="@item.StudentId"><i class="bi bi-pencil-square"></i> Edit </a> |
                <a class="btn btn-outline-info" asp-action="GetDetails" asp-route-id="@item.StudentId"><i class="bi bi-eye"></i> Details </a> |
                <a class="btn btn-danger text-white"><i class="bi bi-trash"></i> Delete </a>
            </td>
        </tr>
        }
    </tbody>
</table>

<div class="text-white float-right" style="position: fixed; right:30px; bottom:90px;">
    <a asp-action="Create" asp-controller="Books" class="btn btn-success"><i class="bi bi-cloud-plus"></i> New Book</a>
</div>